"""
topics_registry.py
------------------
Canonical list of AI architectures for the book assembler.
Each architecture has: id, title, era, category, and dependencies (for ordering).
Add new topics here — the assembler will pick them up on the next run.
"""

TOPICS = [

    # FOUNDATIONAL
    {
        "id": "monte-carlo",
        "title": "Monte Carlo Methods",
        "era": "1940s",
        "category": "foundational",
        "sidebar_order": 1.005,
        "depends_on": [],
        "summary": "Computational algorithms that rely on repeated random sampling to approximate complex mathematical functions.",
    },
    {
        "id": "perceptron",
        "title": "Perceptron",
        "era": "1957-1969",
        "category": "foundational",
        "sidebar_order": 1.010,
        "depends_on": [],
        "summary": "The original single-layer binary classifier; the atom of all neural networks.",
    },
    {
        "id": "multilayer-perceptron",
        "title": "Multilayer Perceptron (MLP)",
        "era": "1986",
        "category": "foundational",
        "sidebar_order": 1.020,
        "depends_on": ["perceptron"],
        "summary": "Stacked layers with non-linear activations, trained via backpropagation.",
    },
    {
        "id": "backpropagation",
        "title": "Backpropagation",
        "era": "1986",
        "category": "foundational",
        "sidebar_order": 1.025,
        "depends_on": ["multilayer-perceptron"],
        "summary": "Chain-rule gradient flow that makes deep network training tractable.",
    },
    {
        "id": "hopfield-network",
        "title": "Hopfield Network",
        "era": "1982",
        "category": "foundational",
        "sidebar_order": 1.030,
        "depends_on": ["perceptron"],
        "summary": "Recurrent energy-minimising memory; ancestor of modern associative memory.",
    },
    {
        "id": "bayesian-neural-network",
        "title": "Bayesian Neural Network (BNN)",
        "era": "1990s",
        "category": "foundational",
        "sidebar_order": 1.040,
        "depends_on": ["multilayer-perceptron"],
        "summary": "Replaces deterministic weights with probability distributions to quantify uncertainty.",
    },
    # CONVOLUTIONAL
    {
        "id": "convolutional-neural-network",
        "title": "Convolutional Neural Network (CNN)",
        "era": "1989-1998",
        "category": "convolutional",
        "sidebar_order": 1.110,
        "depends_on": ["multilayer-perceptron"],
        "summary": "Exploits spatial locality via shared weight filters; backbone of computer vision.",
    },
    {
        "id": "lenet",
        "title": "LeNet-5",
        "era": "1998",
        "category": "convolutional",
        "sidebar_order": 1.120,
        "depends_on": ["convolutional-neural-network"],
        "summary": "LeCun's digit recogniser — the proof-of-concept that made CNNs credible.",
    },
    {
        "id": "alexnet",
        "title": "AlexNet",
        "era": "2012",
        "category": "convolutional",
        "sidebar_order": 1.130,
        "depends_on": ["lenet"],
        "summary": "GPU-powered deep CNN that ignited the modern deep-learning era at ImageNet 2012.",
    },
    {
        "id": "resnet",
        "title": "ResNet (Residual Network)",
        "era": "2015",
        "category": "convolutional",
        "sidebar_order": 1.140,
        "depends_on": ["alexnet"],
        "summary": "Skip connections defeat vanishing gradients, enabling 100+ layer networks.",
    },
    # RECURRENT
    {
        "id": "recurrent-neural-network",
        "title": "Recurrent Neural Network (RNN)",
        "era": "1990",
        "category": "recurrent",
        "sidebar_order": 1.210,
        "depends_on": ["multilayer-perceptron"],
        "summary": "Hidden state loops process arbitrary-length sequences, at the cost of vanishing gradients.",
    },
    {
        "id": "lstm",
        "title": "Long Short-Term Memory (LSTM)",
        "era": "1997",
        "category": "recurrent",
        "sidebar_order": 1.220,
        "depends_on": ["recurrent-neural-network"],
        "summary": "Gated cell state carries information across long sequences without gradient collapse.",
    },
    {
        "id": "gru",
        "title": "Gated Recurrent Unit (GRU)",
        "era": "2014",
        "category": "recurrent",
        "sidebar_order": 1.230,
        "depends_on": ["lstm"],
        "summary": "Streamlined LSTM — two gates instead of three, similar performance, lower compute.",
    },
    #  ATTENTION & TRANSFORMERS
    {
        "id": "attention-mechanism",
        "title": "Attention Mechanism",
        "era": "2015",
        "category": "attention",
        "sidebar_order": 1.310,
        "depends_on": ["lstm"],
        "summary": "Learned soft alignment between encoder states and decoder queries.",
    },
    {
        "id": "transformer",
        "title": "Transformer",
        "era": "2017",
        "category": "attention",
        "sidebar_order": 1.320,
        "depends_on": ["attention-mechanism"],
        "summary": "Self-attention replaces recurrence entirely — 'Attention Is All You Need'.",
    },
    {
        "id": "bert",
        "title": "BERT",
        "era": "2018",
        "category": "attention",
        "sidebar_order": 1.330,
        "depends_on": ["transformer"],
        "summary": "Bidirectional encoder pre-trained with masked language modelling.",
    },
    {
        "id": "gpt",
        "title": "GPT Family (GPT-1 → GPT-4)",
        "era": "2018-2023",
        "category": "attention",
        "sidebar_order": 1.340,
        "depends_on": ["transformer"],
        "summary": "Autoregressive decoder-only transformers scaled to general-purpose intelligence.",
    },
    # GENERATIVE
    {
        "id": "variational-autoencoder",
        "title": "Variational Autoencoder (VAE)",
        "era": "2013",
        "category": "generative",
        "sidebar_order": 1.410,
        "depends_on": ["multilayer-perceptron"],
        "summary": "Probabilistic encoder–decoder learning a structured latent distribution.",
    },
    {
        "id": "generative-adversarial-network",
        "title": "Generative Adversarial Network (GAN)",
        "era": "2014",
        "category": "generative",
        "sidebar_order": 1.420,
        "depends_on": ["multilayer-perceptron"],
        "summary": "Generator vs Discriminator minimax game producing photorealistic samples.",
    },
    {
        "id": "diffusion-model",
        "title": "Diffusion Model (DDPM / Score Matching)",
        "era": "2020-2022",
        "category": "generative",
        "sidebar_order": 1.430,
        "depends_on": ["variational-autoencoder", "transformer"],
        "summary": "Iterative denoising of Gaussian noise learns to reverse a Markov diffusion chain.",
    },
    {
        "id": "flow-matching",
        "title": "Flow Matching",
        "era": "2022-2023",
        "category": "generative",
        "sidebar_order": 1.440,
        "depends_on": ["diffusion-model"],
        "summary": "Continuous normalising flows trained by regressing straight-line probability paths.",
    },
    # GRAPH & GEOMETRIC
    {
        "id": "graph-neural-network",
        "title": "Graph Neural Network (GNN)",
        "era": "2016",
        "category": "graph",
        "sidebar_order": 1.510,
        "depends_on": ["convolutional-neural-network", "attention-mechanism"],
        "summary": "Message passing on arbitrary graph topology — molecules, social nets, knowledge graphs.",
    },
    # REINFORCEMENT LEARNING
    {
        "id": "deep-q-network",
        "title": "Deep Q-Network (DQN)",
        "era": "2013-2015",
        "category": "reinforcement",
        "sidebar_order": 1.610,
        "depends_on": ["convolutional-neural-network"],
        "summary": "Q-value function approximated by CNN — Atari-playing breakthrough.",
    },
    {
        "id": "policy-gradient",
        "title": "Policy Gradient Methods (REINFORCE / PPO / A3C)",
        "era": "1992-2017",
        "category": "reinforcement",
        "sidebar_order": 1.620,
        "depends_on": ["deep-q-network"],
        "summary": "Direct policy optimisation via stochastic gradient ascent on expected return.",
    },
    {
        "id": "rlhf",
        "title": "Reinforcement Learning from Human Feedback (RLHF)",
        "era": "2020-2023",
        "category": "reinforcement",
        "sidebar_order": 1.630,
        "depends_on": ["policy-gradient", "transformer"],
        "summary": "Human preference signal trains a reward model used to fine-tune LLMs via PPO.",
    },
    # MODERN ARCHITECTURES
    {
        "id": "mixture-of-experts",
        "title": "Mixture of Experts (MoE)",
        "era": "1991 / 2022-2024",
        "category": "modern",
        "sidebar_order": 1.710,
        "depends_on": ["transformer"],
        "summary": "Sparse routing activates only K of N expert sub-networks per token — cheap scaling.",
    },
    {
        "id": "state-space-model",
        "title": "State Space Models (Mamba / S4)",
        "era": "2022-2024",
        "category": "modern",
        "sidebar_order": 1.720,
        "depends_on": ["recurrent-neural-network", "transformer"],
        "summary": "Linear-time sequence modelling via structured state-space equations with selective scan.",
    },
    {
        "id": "vision-transformer",
        "title": "Vision Transformer (ViT)",
        "era": "2020",
        "category": "modern",
        "sidebar_order": 1.730,
        "depends_on": ["transformer", "convolutional-neural-network"],
        "summary": "Image patches as tokens — pure self-attention replaces convolution for vision.",
    },
    {
        "id": "multimodal-foundation-model",
        "title": "Multimodal Foundation Models",
        "era": "2021-2024",
        "category": "modern",
        "sidebar_order": 1.740,
        "depends_on": ["vision-transformer", "gpt"],
        "summary": "Unified models bridging text, image, audio, and video with shared representations.",
    },
# FRONTIER
    {
        "id": "emergent-tech",
        "title": "Emergent Technology in AI",
        "era": "Tomorrow",
        "category": "future",
        "sidebar_order": 2.0,
        "depends_on": [],
        "summary": "",
    },
]

# Build a fast lookup by id
TOPICS_BY_ID = {t["id"]: t for t in TOPICS}

# Canonical category order for sidebar grouping
CATEGORY_ORDER = [
    "foundational",
    "convolutional",
    "recurrent",
    "attention",
    "generative",
    "graph",
    "reinforcement",
    "modern",
    "emergent",
]

CATEGORY_LABELS = {
    "foundational": "Foundational",
    "convolutional": "Convolutional Networks",
    "recurrent": "Recurrent Networks",
    "attention": "Attention & Transformers",
    "generative": "Generative Models",
    "graph": "Graph & Geometric",
    "reinforcement": "Reinforcement Learning",
    "modern": "Modern Architectures",
    "emergent": "Emergent Technology",
}
